base: !include base.yaml
lr: 0.001

model: "SDFFNOGNO"
fno_modes: [24, 24, 24]
hidden_channels: 32
use_mlp: true
norm: "group_norm"
domain_padding: 0.125
factorization: "tucker"
r: 0.05
gno_implementation: "torch_scatter" # "torch_scatter" or "PyG"

# dataset
batch_size: 1
# data_module: "CFDSDFDataModule"
# sdf_spatial_resolution: [64, 64, 64]


# dataset
data_module: "TrackBDataModule"
# data_module: "CFDDataModule"
# data_module: "CFDNormalDataModule"

num_epochs: 11
write_to_vtk: true
n_train: 2
n_test: 50

track: "Track_B"
data_dir: "../../xsy_datasets/IJCAI_dataset/aistuio/data_train_B"
test_data_dir: "../../xsy_datasets/IJCAI_dataset/aistuio/data_test_B"
# test_data_dir: "../../xsy_datasets/IJCAI_dataset/aistuio/data_validate_B"

sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points"
Require_sdf: false
closest_points_to_query: false


subsample_train: 1000
subsample_eval: 1000
