base: !include base.yaml

batch_size: 1
lr: 0.001

# optimizer
opt:
  scheduler: "OneCycleLR"

model: "Transolver_conv_sdf"
run_name: "Transolver_conv_sdf"

pretrained_model: 0
pretrained_model_path: "logs/2024-06-15_11-05-41/model-Transolver-5.pt"

# dataset
data_module: "TrackBDataModule"
# data_module: "CFDDataModule"
# data_module: "CFDNormalDataModule"

num_epochs: 1
write_to_vtk: true
n_train: 1
n_test: 1

track: "Track_B"
data_dir: "../../xsy_datasets/IJCAI_dataset/aistuio/data_train_B"
test_data_dir: "../../xsy_datasets/IJCAI_dataset/aistuio/data_test_B"
# test_data_dir: "../../xsy_datasets/IJCAI_dataset/aistuio/data_validate_B"

sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points"
Require_sdf: true
closest_points_to_query: true

#model
n_hidden: 256
n_layers: 2
space_dim: 4
fun_dim: 0
n_head: 8
mlp_ratio: 2
out_dim: 1
slice_num: 32
unified_pos: 0
subsample_train: 1000
subsample_eval: 1000
