base: !include base.yaml
lr: 0.001

model: "SDFFNOGNO"
fno_modes: [24, 24, 24]
hidden_channels: 32
use_mlp: true
norm: "group_norm"
domain_padding: 0.125
factorization: "tucker"
r: 0.05
gno_implementation: "torch_scatter" # "torch_scatter" or "PyG"

# dataset
batch_size: 1
data_module: "CFDSDFDataModule"
sdf_spatial_resolution: [32, 32, 32]
