base: !include base.yaml

batch_size: 1
lr: 0.001

# optimizer
opt:
  scheduler: "OneCycleLR"

model: "Transolver"
run_name: "Transolver"

pretrained_model: 0
pretrained_model_path: "logs/2024-06-15_11-05-41/model-Transolver-5.pt"

# dataset
# data_module: "CFDDataModule"
data_module: "CFDNormalDataModule"

sdf_spatial_resolution: [64, 64, 64]
num_epochs: 500
write_to_vtk: true
n_train: 5
n_test: 5


#model
n_hidden: 256
n_layers: 8
space_dim: 6
fun_dim: 0
n_head: 8
mlp_ratio: 2
out_dim: 1
slice_num: 32
unified_pos: 0
subsample_train: 1
subsample_eval: 1
