base: !include base.yaml

batch_size: 1
lr: 0.001

# optimizer
opt:
  scheduler: "OneCycleLR"

model: "TransGINO"
run_name: "TransGINO"


fno_modes: [24, 24, 24]
hidden_channels: 32
use_mlp: true
norm: "group_norm"
domain_padding: 0.125
factorization: "tucker"
r: 0.05
gno_implementation: "torch_scatter" # "torch_scatter" or "PyG"




pretrained_model: 0
pretrained_model_path: "logs/2024-06-15_11-05-41/model-Transolver-5.pt"

# dataset
# data_module: "CFDDataModule"
# data_module: "CFDNormalDataModule"
data_module: "CFDSDFDataModule"

sdf_spatial_resolution: [64, 64, 64]
num_epochs: 1
write_to_vtk: true
n_train: 2
n_test: 2


#model
n_hidden: 256
n_layers: 8
space_dim: 3
fun_dim: 0
n_head: 8
mlp_ratio: 2
out_dim: 32 #跟hidden_channels一样
slice_num: 32
unified_pos: 0
subsample_train: 1
subsample_eval: 1
