base: !include base.yaml

# Sparse graph parameters
model: "UNet"
use_position_input: True # whether to use position as extra input
out_channels: 1
hidden_channels: 64
num_levels: 4
#base_filters: 64
#depth: 2

run_name: "Unet-v2"

# dataset
batch_size: 4
data_module: "CarDataModule"
sdf_spatial_resolution: [64, 64, 64]
