base: !include base.yaml
run_name: "UNetShapeNetCar"
project_name: "ShapeNetCar"

# train setting
num_epochs: 10
batch_size: 4
eval_batch_size: 1
lr: 0.001
device: cuda:0
save_interval: 50

# model setting
model: "UNet"
in_channels: 4
out_channels: 1 # pressure
num_levels: 4
hidden_channels: 64
use_position_input: True

# dataset setting

# track: "Track_A"
# data_module: "CFDSDFDataModule"
# data_dir: "/home/xusuyong/pythoncode/xsy_datasets/IJCAI_dataset/aistuio/data"
# test_data_dir: "/home/xusuyong/pythoncode/xsy_datasets/IJCAI_dataset/aistuio/data_test_A"

track: "Track_B"
data_module: "TrackBDataModule"
data_dir: "/home/xusuyong/pythoncode/xsy_datasets/IJCAI_dataset/aistuio/data_train_B"
test_data_dir: "/home/xusuyong/pythoncode/xsy_datasets/IJCAI_dataset/aistuio/data_test_B"

n_train: 2
n_test: 2
sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points"

# eval setting
write_to_vtk: True
